execute pathogen#infect()
filetype plugin indent on
syntax on
syn on se title

" Sitewide configuration
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set smartindent
set relativenumber

"set textwidth=80
"set cc=80
"highlight ColorColumn ctermbg=blue
"call matchadd('ColorColumn', '\%81v', 100)

" Configuration for C filetypes
au Filetype c setl sw=8 sts=8 ts=8 expandtab textwidth=80

map <silent> <C-n> :NERDTreeToggle<CR>

" let g:airline_theme='papercolor'
let g:airline_theme='molokai'

set t_Co=256
