execute pathogen#infect()
filetype plugin indent on
syntax on
syn on se title

" Sitewide configuration
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set smartindent
set relativenumber
