# ZSH Installation source
  export ZSH=/home/tim/.oh-my-zsh

export PATH="$HOME/.rbenv/bin:$PATH"
#eval "$(rbenv init -)"

# Current ZSH theme
ZSH_THEME="robbyrussell"

ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

# ZSH plugins
plugins=(
  git
  docker
)

#source $ZSH/oh-my-zsh.sh

# Custom configuration

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

## Custom aliases 

alias open="xdg-open"

# Change keyboard layout -- only works on X11
alias change="setxkbmap"

# See current brightness percentage
#alias bright="cd /sys/class/backlight/intel_backlight/"

# See current battery power
alias bat="upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage"

# Git Aliases
alias gits="git status"
alias gita="git add"
alias gitc="git commit -m"

alias d="deactivate"
alias s="source .venv/bin/activate"
alias v="nvim"
alias vim="nvim"

# AWS aliases
alias ssmi="aws ssm start-session --target"

# Docker aliases
alias clean_vol='docker volume rm $(docker volume ls -q --filter dangling=true) && docker volume prune -f --filter all=true'
alias clean_build='docker builder prune -af && docker buildx prune -af'
alias clean_images='docker image prune -af'
alias clean_prune='docker system prune -af'
alias clean_secrets='docker secret ls -q | xargs docker secret rm'
alias clean_cache='docker buildx prune -af && docker volume prune -f --filter all=true && docker system prune -f && docker builder prune -af'
alias thunderdome='reset; clean_vol; clean_build; clean_images; clean_prune; clean_secrets; docker system df'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - zsh)"
