#! /bin/sh

# compton -b --config ~/.config/compton/compton.conf

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            5
bspc config window_gap              12
bspc config focused_border_color    "#D36823"
bspc config normal_border_color     "#D3D3D3"

bspc config top_padding             25

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

# wal -R
